from dataclasses import dataclass, field
from typing import List, Optional, Literal, Dict, Any
from datetime import datetime, timezone


def now_iso() -> str:
    """Return current UTC time in ISO 8601 format."""
    return datetime.now(timezone.utc).isoformat()


@dataclass
class MemoryBank:
    """Persistent long-term memory body for a character with optimistic lock revision."""
    character_id: str
    body: str = ""
    revision: int = 0
    updated_at: str = field(default_factory=now_iso)


@dataclass
class MemoryCheckpoint:
    """Tracks the last processed assistant message id for a character in a session."""
    character_id: str
    session_id: str
    last_assistant_id: str
    updated_at: str = field(default_factory=now_iso)


@dataclass
class MemoryDraft:
    """An editable memory draft generated by the system before committing."""
    id: str
    character_id: str
    session_id: Optional[str]
    kind: Literal["update", "compression"]
    body: str
    base_revision: int
    source_message_ids: List[str]
    source_digest: str
    through_assistant_id: Optional[str]
    source_turn_count: int
    created_at: str = field(default_factory=now_iso)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "character_id": self.character_id,
            "session_id": self.session_id,
            "kind": self.kind,
            "body": self.body,
            "base_revision": self.base_revision,
            "source_message_ids": self.source_message_ids,
            "source_digest": self.source_digest,
            "through_assistant_id": self.through_assistant_id,
            "source_turn_count": self.source_turn_count,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "MemoryDraft":
        return cls(
            id=data["id"],
            character_id=data["character_id"],
            session_id=data.get("session_id"),
            kind=data["kind"],
            body=data["body"],
            base_revision=data["base_revision"],
            source_message_ids=data.get("source_message_ids", []),
            source_digest=data.get("source_digest", ""),
            through_assistant_id=data.get("through_assistant_id"),
            source_turn_count=data.get("source_turn_count", 0),
            created_at=data.get("created_at", now_iso()),
        )


@dataclass
class CompleteTurn:
    """Represents a paired User and Assistant dialogue turn."""
    user_id: str
    assistant_id: str
    user_content: str
    assistant_content: str
    session_id: str
    character_id: str
    user_created_at: str = field(default_factory=now_iso)
    assistant_created_at: str = field(default_factory=now_iso)
    sequence: Optional[int] = None


@dataclass
class HistorySnippet:
    """Historical conversation snippet recalled from FTS5 BM25 search."""
    turn: CompleteTurn
    token_estimate: int
    session_id: str
    score: float = 0.0


@dataclass
class HistoryRetrievalSettings:
    """Settings for keyword / full-text retrieval from past dialogue."""
    enabled: bool = True
    scope: Literal["current_conversation", "same_character"] = "current_conversation"
    recent_message_count: int = 20
    maximum_results: int = 6
    token_budget: int = 1200


@dataclass
class MemoryGenerationSettings:
    """Settings for LLM when generating memory updates or compressions."""
    model: str = ""
    context_limit: int = 32768
    max_output_tokens: int = 4096
    temperature: float = 0.7
    top_p: float = 1.0


@dataclass
class MemorySettings:
    """Global configuration for the memory subsystem."""
    target_tokens: int = 0  # 0 = unlimited
    auto_generate_enabled: bool = True
    update_interval_turns: int = 10
    maximum_source_user_turns: int = 10
    send_only_new_messages: bool = True
    retrieval: HistoryRetrievalSettings = field(default_factory=HistoryRetrievalSettings)
    update_generation: MemoryGenerationSettings = field(default_factory=MemoryGenerationSettings)
    compression_generation: MemoryGenerationSettings = field(default_factory=MemoryGenerationSettings)


@dataclass
class MemoryTaskStatus:
    """Status tracking for asynchronous memory generation tasks."""
    state: Literal["idle", "queued", "updating", "compressing", "succeeded", "failed", "cancelled"]
    character_id: str
    session_id: Optional[str] = None
    message: Optional[str] = None
    updated_at: str = field(default_factory=now_iso)
